FROM python:3.11-slim

# Install system dependencies including g++
RUN apk add --no-cache gcc g++ musl-dev

# Set working directory
WORKDIR /app

# Copy your application code
COPY /back .

# Copy requirements file and install Python dependencies
RUN pip install --upgrade pip 
RUN pip install --no-cache-dir scikit-learn fastapi uvicorn numpy pandas
    
# Expose the port
EXPOSE 8000

# Command to run the application
CMD ["python", "api_models.py"]

