name: Azure Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas
          pip install fastapi
          pip install uvicorn
          pip install scikit-learn
          pip install pytest
          pip install httpx
          pip install black
          pip install requests

      - name: Format code with Black
        run: black .

      - name: Run tests
        run: pytest tests/

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            az account show

      - name: Azure ACR login
        run: |
          az acr login --name lpb15ajax

      - name: Build and push Docker images
        run: |
          docker build -t b15back -f Dockerfile.back .
          docker tag b15back lpb15ajax.azurecr.io/back:8000
          docker push lpb15ajax.azurecr.io/back:8000
          docker build -t b15front -f Dockerfile.front .
          docker tag b15front lpb15ajax.azurecr.io/front:80
          docker push lpb15ajax.azurecr.io/front:80

      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "password.registry"
          replace: ${{ secrets.IMAGE_REGISTRY_PASSWORD }}
          regex: false
          include: "deploy_az_instance_cont.yml"

      - name: Delete Actual Container Instances
        run: az container delete --resource-group lucie --name lucieb15azcontainer --yes

      - name: Deploy to Azure Container Instances
        run: az container create --resource-group lucie --file deploy_az_instance_cont.yml
